name : "Podcast Generator"
author: "Ray Villalobos"
description: "Generates a feed for a podcast for a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icons: "git-branch"
  color: "red"
inputs:
  email:
    description: The comiter's email address
    required: true
    default: ${( github.actor )}:localhost
  name:
    description: The committer's name
    required: true
    default: ${{github.actor}}
